// SPDX-License-Identifier: MIT



/**
 * THE "HELPER CONFIG" FILE I CREATED , WILL HELP ME TO BE ABLE TO DEPLOY ON A BLOCKCHAIN I WANT(WITHOUT THINKING ABOUT WHICH NETWORK WE ARE CURRENTLY ON).
 * 
 * 
 * THIS IS A "HELPER CONFIG FILE" TO DEPLOY THE CONTRACTS. IN THIS "HELPERCONFIG" CONTRACT, WE ARE GOING TO DO 2 THINGS:
 * 1. DEPLOY  MOCKS WHEN WE ARE ON A LOCAL ANVIL CHAIN.
 * 
 * 2. KEEP TRACK OF THE CONTRACT ADDRESSES OF THE PRICE FEED CONTRACTS ON DIFFERENT NETWORKS (ACROSS DIFF CHAINS), SO THAT WE CAN USE THEM IN OUR DEPLOYMENT SCRIPTS AND TESTS WITHOUT HARD CODING THEM EVERY TIME.
 * 
 * NOTE:: THE "HELPER CONFIG" CONTRACT, WILL HELP US NOT TO HARDCODE THE ADDRESS WHICH WE DID WHEN USING "DEPLOY FUND ME" CONTRACT FILE
 */


pragma solidity ^0.8.18;


//IMPORTING THE SCRIPT LIBRARY FROM FOUNDRY TO CREATE A SCRIPT THAT CAN BE EXECUTED TO DEPLOY CONTRACTS OR INTERACT WITH THEM.
import {Script} from "forge-std/Script.sol";


// IMPORTING "MockV3Aggregator", WHICH IS A MOCK CONTRACT THAT SIMULATES THE BEHAVIOR OF A REAL PRICE FEED AGGREGATOR. THIS IS USEFUL FOR TESTING PURPOSES, AS IT PROVIDES A CONTROLLED ENVIRONMENT WHERE WE CAN DEFINE THE PRICE FEED RESPONSES AND ENSURE THAT OUR CONTRACTS INTERACT WITH THE PRICE FEED AS EXPECTED. THIS IS PARTICULARLY USEFUL FOR TESTING PURPOSES, AS IT PROVIDES A CONTROLLED ENVIRONMENT WHERE WE CAN DEFINE THE PRICE FEED RESPONSES AND ENSURE THAT OUR CONTRACTS INTERACT WITH THE PRICE FEED AS EXPECTED.
import {MockV3Aggregator} from "../test/mocks/MockV3Aggregator.sol";


contract HelperConfig is Script  {
   /**
    * WHAT THIS "HELPER CONFIG" CONTRACT WILL DO IS:
    * - IF WE ARE ON LOCAL ANVIL , WE DEPLOY MOCKS.   OR
    * 
    * - OTHERWISE, GRAB THE EXISTING ADDRESS FROM THE LIVE NETWORK   
    */


   NetworkConfig public activeNetworkConfig;

   

    /**
     * CREATED THIS STATE VARIABLES typically used in a smart contract that interacts with an external price feed (like Chainlink) to determine the price of an asset (e.g., ETH/USD). 
     * 
     * USED TO DEFINE THE DECIMALS AND INITIAL PRICE FOR THE MOCK PRICE FEED. THESE VARIABLES WILL BE USED WHEN DEPLOYING THE MOCK PRICE FEED CONTRACT ON THE ANVIL LOCAL CHAIN. THIS ALLOWS US TO SIMULATE A REALISTIC PRICE FEED ENVIRONMENT FOR TESTING PURPOSES.
     */
    uint8 public constant DECIMALS = 8;
    int256 public constant INITIAL_PRICE = 2000e8; // 2000 USD



   //CREATED A STRUCT TO HOLD THE CONFIGURATION FOR DIFFERENT NETWORKS. THIS STRUCTURE CAN BE EXPANDED IN THE FUTURE TO INCLUDE MORE CONFIGURATION PARAMETERS AS NEEDED.
    struct NetworkConfig {
        address priceFeed;  // ETH/USD THIS IS THE ADDRESS OF THE PRICE FEED CONTRACT THAT OUR "FUNDME" CONTRACT WILL INTERACT WITH TO GET THE PRICE OF ETH IN USD.
    }



    /**
     * A "CONSTRUCTOR FUNCTION" THAT INITIALIZES THE "activeNetworkConfig" BASED ON THE CURRENT CHAIN ID. THIS CONSTRUCTOR CHECKS THE CHAIN ID OF THE NETWORK WE ARE DEPLOYING TO AND SETS THE "activeNetworkConfig" ACCORDINGLY. IF WE ARE ON SEPOLIA, IT USES THE SEPOLIA CONFIG; IF WE ARE ON MAINNET, IT USES THE MAINNET CONFIG; OTHERWISE, IT DEFAULTS TO AN ANVIL CONFIG.
     * 
     * - THIS APPROACH ALLOWS US TO AUTOMATICALLY CONFIGURE OUR DEPLOYMENT SCRIPTS AND TESTS BASED ON THE NETWORK WE ARE WORKING WITH, WITHOUT NEEDING TO MANUALLY CHANGE ADDRESSES OR OTHER CONFIGURATION PARAMETERS.
     * 
     * - INSTEAD OF HARDCODING THE PRICE FEED ADDRESS IN THE DEPLOYMENT SCRIPT, WE ARE USING THIS HELPER CONFIG TO MANAGE THE ADDRESSES FOR DIFFERENT NETWORKS. THIS MAKES OUR DEPLOYMENT SCRIPTS MORE FLEXIBLE AND REUSABLE ACROSS DIFFERENT ENVIRONMENTS.
     */
    constructor() {
        if (block.chainid == 11155111) {
            activeNetworkConfig = getSepoliaEthConfig();
        } else if (block.chainid == 1) {
            activeNetworkConfig = getMainnetEthConfig(); 
        }
         else {
            activeNetworkConfig = getOrCreateAnvilEthConfig();
        }
    }



    function getOrCreateAnvilEthConfig() public  returns (NetworkConfig memory) {
        //WHAT WE NEED HERE (ON THIS ANVIL ETH CONFIG), IS price feed address


        //DID THIS HERE, TO AVOID RE-DEPLOYING OR REFRESHING  CONFIGURATIONS THAT ARE ALREADY BEEN ESTABLISHED.
        if(activeNetworkConfig.priceFeed != address(0)){
            return activeNetworkConfig;
        }


        /**
         * 1. DEPLOYING A MOCK PRICE FEED CONTRACT TO THE ANVIL LOCAL CHAIN AND, 
         * 
         * 2. RETURNING ITS ADDRESS IN THE CONFIGURATION. THIS FUNCTION WOULD TYPICALLY DEPLOY A MOCK CONTRACT AND RETURN ITS ADDRESS.
         */


        //INHERITING THE SCRIPT LIBRARY (ON THE TOP START OF THE PROGRAM: is Script) TO USE ITS FUNCTIONALITY TO DEPLOY CONTRACTS AND INTERACT WITH THE NETWORK. THIS ALLOWS US TO USE FOUNDRY'S SCRIPTING , WHICH IS  vm.startBroadcast() AND vm.stopBroadcast() TO CONTROL WHEN TRANSACTIONS ARE SENT TO THE NETWORK.
        vm.startBroadcast();


        // MockV3Aggregator mockPriceFeed = new MockV3Aggregator(8, 2000e8); // 8 DECIMALS, INITIAL PRICE OF 2000 USD (WITH 8 DECIMALS)

        MockV3Aggregator mockPriceFeed = new MockV3Aggregator(
            DECIMALS,
            INITIAL_PRICE
        ); // 8 DECIMALS, INITIAL PRICE OF 2000 USD (WITH 8 DECIMALS)

        vm.stopBroadcast();


         // DID THIS NetworkConfig , OUTSIDE THE "vm.startBroadcast();" AND "vm.stopBroadcast();" BECAUSE WE DON'T WANT TO BROADCAST THIS TO THE NETWORK. THIS IS JUST A LOCAL VARIABLE THAT WE ARE CREATING TO HOLD THE CONFIGURATION FOR THE ANVIL NETWORK, AND WE DON'T NEED TO SEND THIS AS A TRANSACTION TO THE BLOCKCHAIN.
        NetworkConfig memory anvilConfig = NetworkConfig({
            priceFeed: address(mockPriceFeed)
        });

        return anvilConfig;
    }



    
    function getSepoliaEthConfig() public pure returns (NetworkConfig memory) {
        //WHAT WE NEED HERE (ON THIS SEPOLIA ETH CONFIG), IS price feed address
        NetworkConfig memory sepoliaConfig = NetworkConfig({ 
            priceFeed: 0x694AA1769357215DE4FAC081bf1f309aDC325306
        });
        return sepoliaConfig;
    }



    function getMainnetEthConfig() public pure returns (NetworkConfig memory) {
        //WHAT WE NEED HERE (ON THIS MAINNET ETH CONFIG), IS price feed address
        NetworkConfig memory ethConfig = NetworkConfig({ 
            priceFeed: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
        });
        return ethConfig;
    }


 

}
